import type { Metadata } from "next";
import "./globals.css";
// import Navbar from "../components/navbar";
import { AuthProvider } from "@/context/auth";
import { Toaster } from "@/components/ui/sonner";
import { ServiceProvider } from "@/context/service";
import BackgroundWrapper from "./background-wrapper"; // <-- import it

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased overflow-x-hidden">
        <ServiceProvider>
          <AuthProvider>
            {/* <Navbar /> */}
            <BackgroundWrapper>
              {" "}
              {/* <-- wrap your children */}
              {children}
            </BackgroundWrapper>
            <Toaster richColors />
          </AuthProvider>
        </ServiceProvider>
      </body>
    </html>
  );
}
