import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar";
import { AuthProvider } from "@/context/auth";
import { Toaster } from "@/components/ui/sonner";
import { ServiceProvider } from "@/context/service";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ServiceProvider>
          <AuthProvider>
            <Navbar />
            <div>{children}</div>
            <Toaster richColors />
          </AuthProvider>
        </ServiceProvider>
      </body>
    </html>
  );
}
